Workout_Builder/Controllers/WorkoutController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Diagnostics;
using System.Security.Claims;
using System.Text;
using Workout_Builder.Models;
using Workout_Builder.Properties;
using Workout_Builder.Services;
using Workout_Builder.ViewModels;

namespace Workout_Builder.Controllers
{
    public class WorkoutController : Controller
    {
        private readonly IWorkoutService _workoutContext;
        private readonly ILogger<WorkoutController> _logger;
        private readonly IConfiguration _configuration;
        public readonly int _maxExercises;
        public readonly int _maxSets;

        public WorkoutController(IWorkoutService context, ILogger<WorkoutController> logger, IConfiguration configuration)
        {
            _workoutContext = context;
            _logger = logger;
            _configuration = configuration;
            _maxExercises = _configuration.GetValue<int>("MaxNumExercises");
            _maxSets = _configuration.GetValue<int>("MaxNumSets");
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            //if the user isn't logged in, show them the login screen
            //if (User.Identity != null && !User.Identity.IsAuthenticated)
            //{
            //    return Redirect("Identity/Account/Login");
            //}

            var userID = User.FindFirstValue(ClaimTypes.NameIdentifier) ?? throw new Exception("userID is null");
            var templates = await _workoutContext.GetUserTemplates(userID).ConfigureAwait(false);
            var homeVM = new HomeViewModel()
            {
                WorkoutTemplates = templates,
            };
            return View(homeVM);
        }

        [HttpGet]
        public async Task<IActionResult> NewWorkout()
        {
            var userID = User.FindFirstValue(ClaimTypes.NameIdentifier) ?? throw new Exception("userID is null");
            var templates = await _workoutContext.GetUserTemplates(userID).ConfigureAwait(false);

            var newWorkoutVM = new WorkoutVM()
            {
                Workout = new Workout(),
                //Exercises = new List<Exercise>(),
                ExerciseModels = new List<ExerciseVM>(),
                //NewExercise = new Exercise(),
                //AddExercise = false,
                NumExercises = 1,
                MaxNumExercises = _maxExercises,
                MaxNumSets = _maxSets,
                CurrentTemplates = templates,
            };

            var exerciseList = await _workoutContext.GetExerciseSelectList();
            for (int i = 0; i < _maxExercises; i++)
            {
                var newModel = new ExerciseVM(i, _maxSets)
                {
                    ExerciseList = exerciseList,
                };

                newWorkoutVM.ExerciseModels.Add(newModel);
            }

            return View(newWorkoutVM);
        }

        [HttpPost]
        public async Task<IActionResult> NewWorkout(WorkoutVM newWorkoutVM)
        {
            if (newWorkoutVM == null || newWorkoutVM.ExerciseModels == null)
            {
                throw new Exception("View Model is missing data");
            }

            if (ModelState.IsValid)
            {
                if (newWorkoutVM.Workout == null)
                {
                    throw new Exception("Workout is null");
                }

                //create workout for current user
                var userID = User.FindFirstValue(ClaimTypes.NameIdentifier) ?? throw new Exception("UserId is null");
                newWorkoutVM.Workout.UserId = userID;

                //add workout to database
                int workoutID = await _workoutContext.AddWorkout(newWorkoutVM.Workout).ConfigureAwait(false);

                //add exercises to database
                for (int i = 0; i < newWorkoutVM.NumExercises; i++)
                {
                    //obtain exercise information
                    var model = newWorkoutVM.ExerciseModels[i];
                    var exerciseType = await _workoutContext.GetExerciseByName(model.Name);

                    //use custom name field if the entered exercise doesn't match any in the db
                    string customType = "";
                    if (exerciseType == null)
                    {
                        customType = model.Name;
                    }

                    //create json string that records individual sets info
                    string setsJsonString = "";
                    if (model.CustomSets)
                    {
                        //ensure unused sets are zeroed out
                        for(int j = model.NumSets; j < _maxSets; j++)
                        {
                            model.SetsList[j].Reps = 0;
                            model.SetsList[j].Weight = 0;
                        }

                        setsJsonString = _workoutContext.CreateSetJsonString(model.SetsList);
                    }

                    //build new exercise
                    var newExercise = new Exercise()
                    {
                        Workout = newWorkoutVM.Workout,
                        Order = model.Order,
                        NumSets = model.NumSets,
                        MasterReps = model.MasterReps,
                        MasterWeight = model.MasterWeight,
                        ExerciseType = exerciseType,
                        CustomExerciseName = customType,
                        IsPounds = newWorkoutVM.IsPounds,
                        CustomSets = model.CustomSets,
                        SetsJsonString = setsJsonString,
                    };

                    int exerciseID = await _workoutContext.AddExercise(newExercise);
                }

                return RedirectToAction("Index");
            }

            return View(newWorkoutVM);
        }

        [HttpGet]
        [Route("Workout/EditWorkout/{workoutID:int}")]
        public async Task<IActionResult> EditWorkout(int workoutID)
        {
            //find workout and exercises
            var workout = await _workoutContext.GetWorkout(workoutID) ?? throw new Exception("No workout found with ID: " + workoutID);
            var exercises = await _workoutContext.GetExercises(workoutID) ?? throw new Exception("No exercises found for workout: " + workoutID);

            //create workout viewmodel
            var newWorkoutVM = new WorkoutVM()
            {
                Workout = workout,
                ExerciseModels = new List<ExerciseVM>(),
                NumExercises = exercises.Count(),
                MaxNumExercises = _maxExercises,
                MaxNumSets = _maxSets,
            };

            //create exercise viewmodels
            var exerciseList = await _workoutContext.GetExerciseSelectList();
            for (int i = 0; i < _maxExercises; i++)
            {
                var newModel = new ExerciseVM();
                if(i < exercises.Count())
                {
                    //existing exercises
                    newModel = new ExerciseVM(exercises[i], _maxSets);
                }
                else
                {
                    //blank exercises
                    newModel = new ExerciseVM(i, _maxSets);
                }

                newModel.ExerciseList = exerciseList;
                newWorkoutVM.ExerciseModels.Add(newModel);
            }

            return View(newWorkoutVM);
        }

        [HttpPost]
        public async Task<IActionResult> EditWorkout(WorkoutVM newWorkoutVM)
        {
            if (newWorkoutVM == null || newWorkoutVM.ExerciseModels == null)
            {
                throw new Exception("View Model is missing data");
            }

            //don't save changes if this user didn't create the workout
            var userID = User.FindFirstValue(ClaimTypes.NameIdentifier) ?? throw new Exception("UserId is null");
            if(newWorkoutVM.Workout.UserId != userID)
            {
                return View(newWorkoutVM);
            }

            if (ModelState.IsValid)
            {
                //create workout for current user
                newWorkoutVM.Workout.UserId = userID;

                //add workout to database
                int workoutID = await _workoutContext.AddWorkout(newWorkoutVM.Workout).ConfigureAwait(false);

                //add exercises to database
                for (int i = 0; i < newWorkoutVM.NumExercises; i++)
                {
                    //obtain exercise information
                    var model = newWorkoutVM.ExerciseModels[i];
                    var exerciseType = await _workoutContext.GetExerciseByName(model.Name);

                    //use custom name field if the entered exercise doesn't match any in the db
                    string customType = "";
                    if (exerciseType == null)
                    {
                        customType = model.Name;
                    }

                    //create json string that records individual sets info
                    string setsJsonString = "";
                    if (model.CustomSets)
                    {
                        setsJsonString = _workoutContext.CreateSetJsonString(model.SetsList);
                    }

                    //build new exercise
                    var newExercise = new Exercise()
                    {
                        Workout = newWorkoutVM.Workout,
                        Order = model.Order,
                        NumSets = model.NumSets,
                        MasterReps = model.MasterReps,
                        MasterWeight = model.MasterWeight,
                        ExerciseType = exerciseType,
                        CustomExerciseName = customType,
                        IsPounds = newWorkoutVM.IsPounds,
                        CustomSets = model.CustomSets,

Workout_Builder/Views/Shared/PartialForm.cshtml
@model Workout_Builder.ViewModels.NewWorkoutVM

<form method="post" id="EditForm" enctype="multipart/form-data" onsubmit="return clientValidation()">

    @* <label asp-for="ExerciseType.Name" class="control-label">Exercise</label>
    <input asp-for="ExerciseType.Description" type="text" class="form-control" /> *@



</form>

Workout_Builder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Workout_Builder</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Workout_Builder.styles.css" asp-append-version="true" />
    <script src="jquery-3.7.1.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Workout" asp-action="Index">Workout_Builder</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Workout" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Workout" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Workout_Builder - <a asp-area="" asp-controller="Workout" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Workout_Builder/Views/Shared/_WorkoutEditor.cshtml
@model Workout_Builder.ViewModels.WorkoutVM

<div>
    <form method="post" id="addForm" enctype="multipart/form-data" onsubmit="return clientValidation()">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="Workout.Name" class="control-label">Workout Name</label>
            <input asp-for="Workout.Name" type="text" class="form-control" />
            <span asp-validation-for="Workout.Name" class="text-danger"></span>
            <span id="noNameError" class="text-danger" style="display:none;">Workout name is required.</span>
        </div>

        <div id="exercisesSection">
            <h3 id="exercisesLabel">Exercises</h3>
            @{
                for (int i = 0; i < Model.ExerciseModels.Count; i++)
                {
                    //if this variable is set then the div will be hidden
                    var hiddenDivStyling = "";
                    if (i >= Model.NumExercises)
                    {
                        hiddenDivStyling = "HideOnLoad";
                    }

                    <div id="exerciseDiv_@i" class="row ExerciseDiv @hiddenDivStyling">
                        <br />

                        <div class="row NewExerciseInputs">
                            <div class="action-item col-sm-4 target">
                                <div class="form-group">
                                    <label class="control-label">Exercise Name</label>
                                    @if (Model.ExerciseModels[i].Name == "0")
                                    {
                                        <input asp-for="ExerciseModels[i].Name" value="" id="exerciseNameInput_@i" type="search" class="form-control ExerciseName" autocomplete="off" />
                                    }
                                    else
                                    {
                                        <input asp-for="ExerciseModels[i].Name" id="exerciseNameInput_@i" type="search" class="form-control ExerciseName" autocomplete="off" />
                                    }
                                    <span asp-validation-for="ExerciseModels[i].Name" class="text-danger"></span>
                                    <div class="AutoCompleteDiv"></div>
                                </div>
                            </div>

                            <div class="action-item col-sm-2 target">
                                <div class="form-group">
                                    <label asp-for="ExerciseModels[i].NumSets" class="control-label">Number of sets</label>
                                    <select asp-for="ExerciseModels[i].NumSets" class="form-select NumSetsInput" aria-label="Default select">
                                        <option selected value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                        <option value="6">6</option>
                                        <option value="7">7</option>
                                        <option value="8">8</option>
                                        <option value="9">9</option>
                                    </select>
                                </div>
                            </div>

                            <div class="action-item col-sm-2 target">
                                <div class="form-group">
                                    <label asp-for="ExerciseModels[i].MasterReps" class="control-label">Number of reps</label>
                                    @if (Model.ExerciseModels[i].CustomSets)
                                    {
                                        <input asp-for="ExerciseModels[i].MasterReps" type="number" class="form-control MasterRepsInput" readonly />
                                    }
                                    else
                                    {
                                        <input asp-for="ExerciseModels[i].MasterReps" type="number" class="form-control MasterRepsInput" />
                                    }
                                </div>
                            </div>

                            <div class="action-item col-sm-2 target">
                                <div class="form-group">
                                    <label asp-for="ExerciseModels[i].MasterWeight" class="control-label">Weight</label>
                                    <div style="display: flex;">
                                        @if (Model.ExerciseModels[i].CustomSets)
                                        {
                                            <input asp-for="ExerciseModels[i].MasterWeight" type="number" class="form-control MasterWeightInput" style="flex: 1;" readonly />
                                        }
                                        else
                                        {
                                            <input asp-for="ExerciseModels[i].MasterWeight" type="number" class="form-control MasterWeightInput" style="flex: 1;" />
                                        }
                                        <span style="flex: 1;">&nbsp Lbs</span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        @* show custom sets if this exercise has them *@
                        @if (Model.ExerciseModels[i].CustomSets)
                        {
                            <div class="row CustomRowSets">
                                @for (int j = 0; j < 9; j++)
                                {
                                    int setNumber = j + 1;
                                    if (setNumber <= Model.ExerciseModels[i].NumSets)
                                    {
                                        hiddenDivStyling = "";
                                    }
                                    else
                                    {
                                        hiddenDivStyling = "HideOnLoad";
                                    }
                                    <div class="CustomSetRow CustomSet_@j @hiddenDivStyling">
                                        <span class="SetNumberSpan">Set @setNumber</span>
                                        <div class="action-item col-sm-2 Inline">
                                            <div class="form-group">
                                                <label asp-for="ExerciseModels[i].SetsList[j].Reps" class="control-label">Number of reps</label>
                                                <input asp-for="ExerciseModels[i].SetsList[j].Reps" type="number" class="form-control RepsInput" />
                                            </div>
                                        </div>

                                        <div class="action-item col-sm-2 Inline">
                                            <div class="form-group">
                                                <label asp-for="ExerciseModels[i].SetsList[j].Weight" class="control-label">Weight</label>
                                                <div style="display: flex;">
                                                    <input asp-for="ExerciseModels[i].SetsList[j].Weight" type="number" class="form-control WeightInput" style="flex: 1;" />
                                                    <span style="flex: 1;">&nbsp Lbs</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        }
                        @* hide all custom sets if this exercise doesn't have any *@
                        else
                        {
                            <div class="row CustomRowSets HideOnLoad">
                                @for (int j = 0; j < 9; j++)
                                {
                                    int setNumber = j + 1;
                                    <div class="CustomSetRow CustomSet_@j HideOnLoad">
                                        <span class="SetNumberSpan">Set @setNumber</span>
                                        <div class="action-item col-sm-2 Inline">
                                            <div class="form-group">
                                                <label asp-for="ExerciseModels[i].SetsList[j].Reps" class="control-label">Number of reps</label>
                                                <input asp-for="ExerciseModels[i].SetsList[j].Reps" type="number" class="form-control RepsInput" />
                                            </div>
                                        </div>

                                        <div class="action-item col-sm-2 Inline">
                                            <div class="form-group">
                                                <label asp-for="ExerciseModels[i].SetsList[j].Weight" class="control-label">Weight</label>
                                                <div style="display: flex;">
                                                    <input asp-for="ExerciseModels[i].SetsList[j].Weight" type="number" class="form-control WeightInput" style="flex: 1;" />
                                                    <span style="flex: 1;">&nbsp Lbs</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        }

                        @* delete and customize sets buttons *@
                        <div class="action-item col-sm-4 target">
                            <div class="form-group">
                                <br />
                                @* change button name if custom sets are showing *@
                                @if (Model.ExerciseModels[i].CustomSets)
                                {
                                    <button type="button" id="CustomizeSetsButton_@Model.ExerciseModels[i].Order" class="btn btn-success col-sm-5 CustomizeSetsButton">Hide Sets</button>
                                }
                                else
                                {
                                    <button type="button" id="CustomizeSetsButton_@Model.ExerciseModels[i].Order" class="btn btn-success col-sm-5 CustomizeSetsButton">Customize Sets</button>
                                }

                                <button type="button" class="DeleteExercise btn btn-danger col-sm-5">Delete Exercise</button>
                            </div>
                        </div>

                        @* hidden model properties for this exercise *@
                        <input asp-for="ExerciseModels[i].Order" class="OrderInput" hidden />
                        <input asp-for="ExerciseModels[i].CustomSets" class="CustomSetsInput" hidden />
                    </div>
                }
            } @* end of exercises for loop *@
        </div>

        <div>
            <button id="addExercise" type="button" class="btn btn-warning">Add Exercise</button>
            <span id="maxExercisesMessage" class="text-danger HideOnLoad">&nbspCannot add more than @Model.MaxNumExercises exercises.</span>
        </div>

        <br />
        <button id="submitButton" type="button" class="btn btn-primary" onclick="PrepareClientValidation()">Create Workout</button>
        <button id="submitForm" type="submit" hidden></button>
        <div id="submitSpinner" class="spinner-border text-primary" role="status" hidden></div>

        @* hidden model properties for workout *@
        <div>
            <input id="numExercises" asp-for="NumExercises" hidden />
            <input asp-for="CurrentTemplates" hidden />
            <input id="maxExercises" asp-for="MaxNumExercises" hidden />
            <input id="maxSets" asp-for="MaxNumSets" hidden />
        </div>
    </form>
</div>

Workout_Builder/Views/Shared/_WorkoutList.cshtml
@model List<Workout>

<div>
    <h2>Workout Templates</h2>
    <div class="WorkoutTemplates">
        @if (Model != null)
        {
            foreach (var workout in Model)
            {
                <div class="FlexContainer">
                    <h4 class="WorkoutName">@workout.Name</h4>
                    <a asp-action="EditWorkout" asp-route-id="@workout.Id" class="">View Workout</a>
                    <br />
                </div>
            }
        }
    </div>
</div>